### ISSUE TITLE
TokenGenerator should now accept a parameter of type Interface

### ISSUE THREAD

**Issue by BenKnigge** [appleboy/gin-jwt#125]
TokenGenerator only accepts  type string but the payload function now accepts a parameter of type Interface. TokenGenerator should be updated to also accept type interface or a struct consisting of  an id string and an interface. 

type TokenData struct {
    UserID string,
    Payload interface{}
}
Let me know your thoughts  and I could submit a pr

**Comment by appleboy** [comment]
fixed in https://github.com/appleboy/gin-jwt/pull/126
