### ISSUE TITLE
c.ShouldBind(&loginVals) problem in auth_jwt.go

### ISSUE THREAD

**Issue by rcholic** [appleboy/gin-jwt#133]
I use the `LoginHandler` for my route/controller to handle user login, and the login credentials is POSTed in the form of json. I found this line 350 in auth_jwt.go problematic, as it throws `ErrMissingLoginValues` error.

```go
if c.ShouldBind(&loginVals) != nil
```
After changing it to `c.ShouldBinJSON`, it works for me. Does anyone else have this problem, too?

**Comment by appleboy** [comment]
@rcholic Could you post example code? It is working for unit testing.

see 

https://github.com/appleboy/gin-jwt/blob/2897c31b882872a2634a4324b877054d3e541786/auth_jwt_test.go#L327-L342

**Comment by rcholic** [comment]
When the `Content-Type` is not specified to **JSON** in the request, this `c.ShouldBind(&loginVals)` just returns error, leading to the problem I reported. 

If you expect to receive JSON input, please use the explicit form `c.ShouldBindJSON(&loginVals)` in your code. Thank you
