### ISSUE TITLE
gin.NoRoute causes jwt.ExtractClaims(ctx) to return empty jwt.MapClaims

### ISSUE THREAD

**Issue by UnAfraid** [appleboy/gin-jwt#144]
As title says gin.NoRoute causes jwt.ExtractClaims(ctx) to return empty jwt.MapClaims

```go
router := gin.New()
// .. 
router.NoRoute(func(ctx *gin.Context) {
	claims := jwt.ExtractClaims(ctx)
	logrus.Infof("NoRoute claims: %#v", claims)
	ctx.HTML(http.StatusNotFound, "404.html", gin.H{
		"title": "Page Title",
                "claims": claims,
	})
})
```

And result is: `NoRoute claims: jwt.MapClaims{}`

Seems like the `middlewareImpl` is not being called

**Comment by appleboy** [comment]
See the following example. 

https://github.com/appleboy/gin-jwt/blob/3d7a696f4b423d32c37c006f9d3946f2fbf2c845/example/server.go#L108-L112
