### ISSUE TITLE
Example Issue: Headers were already written. Wanted to override status code 400 with 401

### ISSUE THREAD

**Issue by actumn** [appleboy/gin-jwt#150]
When I followed your changed example, I tested with json that doesn't contains required key (like `{"username":"admin"}`) and I met the warning log like below.
```
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 400 with 401
```
From below, because of field validation, Authenticator returns error and  `c.Bind` writes Content-Type header as "text/plain"
https://github.com/appleboy/gin-jwt/blob/0be8d339e41c34de92ebb05e960287a33e33c22f/example/basic/server.go#L59-L61
https://github.com/gin-gonic/gin/blob/0da5b0c85ac2539e775a7e63aebf3e0b5808dab4/context.go#L496-L507
```
// Bind checks the Content-Type to select a binding engine automatically,
// Depending the "Content-Type" header different bindings are used:
//     "application/json" --> JSON binding
//     "application/xml"  --> XML binding
// otherwise --> returns an error.
// It parses the request's body as JSON if Content-Type == "application/json" using JSON or XML as a JSON input.
// It decodes the json payload into the struct specified as a pointer.
// It writes a 400 error and sets Content-Type header "text/plain" in the response if input is not valid.
func (c *Context) Bind(obj interface{}) error {
	b := binding.Default(c.Request.Method, c.ContentType())
	return c.MustBindWith(obj, b)
}
```
However, jwt middleware also use unauthorized function for handling error response.  
https://github.com/appleboy/gin-jwt/blob/0be8d339e41c34de92ebb05e960287a33e33c22f/auth_jwt.go#L356-L361
https://github.com/appleboy/gin-jwt/blob/0be8d339e41c34de92ebb05e960287a33e33c22f/example/basic/server.go#L82-L87

Therefore, it can occur some problem (like response with content-type as "text/plain", not "application/json)
I thinks `c.Bind` should be changed to `c.ShouldBind`
Can you check it?

**Comment by appleboy** [comment]
fixed by https://github.com/appleboy/gin-jwt/pull/151
