### ISSUE TITLE
MiddlewareInit() being called from LoginHandler

### ISSUE THREAD

**Issue by gabbottron** [appleboy/gin-jwt#153]
Why is the MiddlewareInit function being called from the LoginHandler? When the authorized routes are being set up, MiddlewareFunc calls MiddlewareInit and returns the gin.HandlerFunc. I would assume initialization code should only be called when the program is starting up, but in the current implementation it is being called every time the login route is hit.

**Comment by appleboy** [comment]
@gabbottron You are right. I will change the behavior.
