### ISSUE TITLE
Function signature mismatch for IdentityHandler()

### ISSUE THREAD

**Issue by gabbottron** [appleboy/gin-jwt#158]
Using the basic server example in master, I implemented the IdentityHandler function with the required signature to satisfy the interface: IdentityHandler: func(claims jwt.MapClaims) interface{}

**I get this error:**  server.go:83:18: cannot use func literal (type func("github.com/appleboy/gin-jwt".MapClaims) interface {}) as type func("gopkg.in/dgrijalva/jwt-go.v3".MapClaims) interface {} in field value

If I change the type to simply MapClaims in auth_jwt.go more problems will crop up because internally it's using functions on MapClaims that aren't defined in your jwt package. I forked your repo and made a change to supply the context to the IdentityHandler function instead of the MapClaims object. In the middlewareImpl() function I just made sure to set the JWT_PAYLOAD into the context before calling the IdentityHandler. I think this is a better approach because it abstracts away interaction with the JWT claims to only your middleware instead of also in one function that must be implemented in the server. This way I only have to work with the context instead of the JWT claims.

You can check out the changes I made here: https://github.com/gabbottron/gin-jwt

I also put in an extra example server that implements IdentityHandler with a custom User object. Feel free to comment if you have thoughts around this. Thanks!

**Comment by appleboy** [comment]
@gabbottron So you just change 

```go
IdentityHandler func(jwt.MapClaims) interface{}
```

to 

```go
IdentityHandler func(*gin.Context) interface{}
```

and MapClaims is open function defined in `auth_jwt.go`

https://github.com/appleboy/gin-jwt/blob/df10efdc5167e0a370b5ff5118363180e3298ed7/auth_jwt.go#L17

**Comment by appleboy** [comment]
I got your point. Will make new PR to fix this issue.

**Comment by appleboy** [comment]
See https://github.com/appleboy/gin-jwt/pull/159 PR

**Comment by gabbottron** [comment]
Thanks! I really appreciate your work on this project. I'd be happy to
contribute :)
