### ISSUE TITLE
MapClaims and jwt.MapClaims

### ISSUE THREAD

**Issue by actumn** [appleboy/gin-jwt#167]
Somewhere uses own MapClaims
https://github.com/appleboy/gin-jwt/blob/bfaf3eec539641d8b561361b957f44d3b1d6997a/auth_jwt.go#L60

And somewhere returns jwt.MapClaims
https://github.com/appleboy/gin-jwt/blob/bfaf3eec539641d8b561361b957f44d3b1d6997a/auth_jwt.go#L595-L602

Shouldn't it be unified?

**Comment by appleboy** [comment]
You don't import `github.com/dgrijalva/jwt-go` to use `jwt.MapClaims` and only just use `MapClaims` from `gin-jwt` package.

```go
		PayloadFunc: func(data interface{}) jwt.MapClaims {
			if v, ok := data.(*User); ok {
				return jwt.MapClaims{
					identityKey: v.UserName,
				}
			}
			return jwt.MapClaims{}
		},
```

See Readme.

**Comment by actumn** [comment]
What I was going to do is like below
```
func ConvertClaims(claims jwt.MapClaims) UserClaims {
	return UserClaims{
		UserId:     uint(claims["user_id"].(float64)),
		UserRole:   UserRole(claims["user_role"].(float64)),
		UserRoleId: uint(claims["user_role_id"].(float64)),
	}
}
userClaims := ConvertClaims(jwt.ExtractClaims(c))
```
Compiler says, `Cannot use 'jwt.ExtractClaims(type "github.com/dgrijalva/jwt-go".jwt.MapClaims) as type "github.com/appleboy/gin-jwt".jwt.MapClaims`  
So I just wonder why ExtractClaims returns `"github.com/dgrijalva/jwt-go".jwt.MapClaims`  
Could you say about it?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@actumn See https://github.com/appleboy/gin-jwt/pull/168 PR
