### ISSUE TITLE
setCookie used fixed key "JWTToken"

### ISSUE THREAD

**Issue by newly12** [appleboy/gin-jwt#174]
hi, 

I have some questions..

* can this be configurable

```golang
	// set cookie
	if mw.SendCookie {
		maxage := int(expire.Unix() - time.Now().Unix())
		c.SetCookie(
			"JWTToken",
			tokenString,
			maxage,
			"/",
			mw.CookieDomain,
			mw.SecureCookie,
			mw.CookieHTTPOnly,
		)
	}
```

* in example, cookie is named as "jwt", kind of confusing and when copy the example code, it takes time to find out this inconsistence.  
```golang
		TokenLookup: "header: Authorization, query: token, cookie: jwt",
```

**Comment by appleboy** [comment]
Already add `CookieName` in jwt package.

**Comment by appleboy** [comment]
@newly12 

https://github.com/appleboy/gin-jwt/blob/7e28a7a4c79817c134c7c58e656f6e498da4ce6c/auth_jwt.go#L126-L127

**Comment by newly12** [comment]
@appleboy thanks for the prompt action
