### ISSUE TITLE
Can not set certain GinJWTMiddleware fields

### ISSUE THREAD

**Issue by gluaxspeed** [appleboy/gin-jwt#182]
When trying to set fields such as CookieHTTPOnly, CookieDomain, and CookieName they return an unknown field error.

**Comment by appleboy** [comment]
@gluaxspeed Post your source code.

**Comment by gluaxspeed** [comment]
`var authMiddleware = &jwt.GinJWTMiddleware{
	Realm:          "localhost:5555",
	Key:            []byte("tyr makes you tear"),
	Timeout:        time.Hour,
	MaxRefresh:     time.Hour * 24,
	Authenticator:  Authenticator,
	Authorizator:   Authorizator,
	Unauthorized:   Unauthorized,
	TokenLookup:    "header:Authorization",
	TokenHeadName:  "Bearer",
	TimeFunc:       time.Now,
	SendCookie:     true,
	SecureCookie:   false,
	CookieHTTPOnly: true,
	CookieDomain:   "localhost:5555",
	CookieName:     "token",
}`

results in the following errors from go vet.

# command-line-arguments [command-line-arguments.test]
./jwt.go:178:2: unknown field 'CookieHTTPOnly' in struct literal of type "github.com/appleboy/gin-jwt".GinJWTMiddleware
./jwt.go:179:2: unknown field 'CookieDomain' in struct literal of type "github.com/appleboy/gin-jwt".GinJWTMiddleware
./jwt.go:180:2: unknown field 'CookieName' in struct literal of type "github.com/appleboy/gin-jwt".GinJWTMiddleware

**Comment by gluaxspeed** [comment]
Am I doing something dumb wrong? I still have yet to manage to fix this issue.

**Comment by appleboy** [comment]
Please update gin-jwt to the latest version. I can't reproduce this issue.

**Comment by gluaxspeed** [comment]
gluax@gluax ~/dev/tyr/backend (download-submission*) $ go get -u "github.com/appleboy/gin-jwt"
gluax@gluax ~/dev/tyr/backend (download-submission*) $ go build                               
# backend/api/auth
api/auth/jwt.go:25:2: unknown field 'CookieHTTPOnly' in struct literal of type "github.com/appleboy/gin-jwt".GinJWTMiddleware
gluax@gluax ~/dev/tyr/backend (download-submission*) $
