### ISSUE TITLE
How to fix go mod incompatible dependency

### ISSUE THREAD

**Issue by gluaxspeed** [appleboy/gin-jwt#194]
Go mod still marks this dependency as incompatible despite #171 saying this should be resolved. Unless you need to do something outside of **go get github.com/appleboy/gin-jwt** this should be documented in readme. As this causes people to be unable to use features such as jwt.New(&jwt.GinJWTMiddleware{}) with the error **api/auth/jwt.go:16:22: undefined: "github.com/appleboy/gin-jwt".New**

**Comment by gluaxspeed** [comment]
This is fixed by ** go get github.com/appleboy/gin-jwt@ca1084e5d5a2912d883a425834a3b642c62dc9cd** which is the commit version ("but I feel this should not be needed?)

**Comment by sarovin** [comment]
I have the same issue with dep. 
I have fixed it with this change in Gopkg.toml :
FROM
```go
[[constraint]]
  name = "github.com/appleboy/gin-jwt"
  version = "2.5.0"
```
TO
```go
[[constraint]]
  branch = "master"
  name = "github.com/appleboy/gin-jwt"
```

**Comment by appleboy** [comment]
release the v2.6.0  See https://github.com/appleboy/gin-jwt/releases/tag/v2.6.0

**Comment by smilemakc** [comment]
```
$ go list -m -versions github.com/appleboy/gin-jwt  
```

github.com/appleboy/gin-jwt 
v1.0.0 
v1.0.1 
v2.0.0+incompatible 
v2.1.0+incompatible
v2.1.1+incompatible 
v2.1.2+incompatible 
v2.2.0+incompatible 
v2.3.0+incompatible
v2.3.1+incompatible 
v2.4.0+incompatible 
v2.5.0+incompatible

where v2.6.0?


```
go get github.com/appleboy/gin-jwt@2.6.0 
```

go: finding github.com/appleboy/gin-jwt 2.6.0
go get github.com/appleboy/gin-jwt@2.6.0: unknown revision 2.6.0

**Comment by appleboy** [comment]
@smilemakc Try the `go get github.com/appleboy/gin-jwt/v2`

**Comment by estebanborai** [comment]
Hi, I had the same issue and installed the package without `/v2` (`go get github.com/appleboy/gin-jwt`).

Then ran `dep ensure` and got the dependencies running in my project.

My Gopkg.lock have a reference to `gin-jwt`:

```
[[projects]]
  digest = "1:69f5f537d94e41742dfffed2f11ba0f95d6a803cf6ad63ac79e20b6a27948aca"
  name = "github.com/appleboy/gin-jwt"
  packages = ["."]
  pruneopts = "UT"
  revision = "8135d5fe23da9021d7dceeee4d60e41b3a66a46c"
  version = "v2.6.2"
```

But Gopkg.toml have no references to the same.
