### ISSUE TITLE
integrate error

### ISSUE THREAD

**Issue by thanhngvpt** [appleboy/gin-jwt#203]
Hi all,
I've an exist go project so i try to add example into my project but got this error 
![Screen Shot 2019-05-07 at 11 04 53 AM](https://user-images.githubusercontent.com/19367683/57271056-247d5e00-70b8-11e9-9fa1-32723e941c31.png)
But i clone then run `go run example/basic/server.go` it works well.
My current project using go mod
How to i integrate it? Is it relate to install dependencies by go module?
Thanks

**Comment by appleboy** [comment]
@thanhngvpt Please try the go get `github.com/appleboy/gin-jwt/v2`
