### ISSUE TITLE
Importing module with go get fails

### ISSUE THREAD

**Issue by 107g** [appleboy/gin-jwt#208]
Hello,

I get the following error when trying to import the module using go get:

```
$ go get github.com/appleboy/gin-jwt/v2
go: github.com/appleboy/gin-jwt/v2@v2.6.0: go.mod has non-.../v2 module path "github.com/appleboy/gin-jwt" (and .../v2/go.mod does not exist) at revision v2.
6.0
go: error loading module requirements
```

I haven't had that issue with any other Go module I had to install.

**Comment by Sadzeih** [comment]
I have the same issue!

**Comment by peuek** [comment]
We have issues with that also

**Comment by appleboy** [comment]
Fixed in https://github.com/appleboy/gin-jwt/commit/1806244dcfbb126cef480b234b23093494bd3df0

**Comment by appleboy** [comment]
bump to version v2.6.1
