### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tomasvolta** [appleboy/gin-jwt#21]
Hi thanks for this.
I'm using this middleware but can't help notice the typo here. Thanks!

https://github.com/appleboy/gin-jwt/blob/master/auth_jwt.go#L143

**Comment by appleboy** [comment]
@tomasvolta I will fix it. THanks.

**Comment by appleboy** [comment]
@tomasvolta Please update gin-jwt by following command.

```
$ go get -u github.com/appleboy/gin-jwt
```
