### ISSUE TITLE
go get github.com/appleboy/gin-jwt/v2 doesn't seem to work

### ISSUE THREAD

**Issue by Alv3s** [appleboy/gin-jwt#210]
I'm new to go, but this is my first time facing this kind of issue, and since it's very basic, I'm not sure what the issue is about. Tryign to install this library always gets me the following error:

```
C:\Repo\onoff-api>go get github.com/appleboy/gin-jwt/v2
package github.com/appleboy/gin-jwt/v2: cannot find package "github.com/appleboy/gin-jwt/v2" in any of:
        c:\go\src\github.com\appleboy\gin-jwt\v2 (from $GOROOT)
        C:\Users\User\go\src\github.com\appleboy\gin-jwt\v2 (from $GOPATH)
        C:\Repo\onoff-api\src\github.com\appleboy\gin-jwt\v2
```
Go Get is working fine with other packages (tried on two different machines).

**Comment by alanihre** [comment]
I am facing the same problem but I managed to solve it by going to $GOPATH\src\github.com\appleboy\gin-jwt and putting all the files inside a catalog called "v2.

**Comment by LucasFrecia** [comment]
It works if you remove the /v2. 

`go get github.com/appleboy/gin-jwt`

**Comment by appleboy** [comment]
@Alv3s @alanihre @LucasFrecia Hi guys, Do you use the go module or vendor tool like `dep` or `govendor`?

**Comment by TGPTIAlves** [comment]
> @Alv3s @alanihre @LucasFrecia Hi guys, Do you use the go module or vendor tool like `dep` or `govendor`?

I use govendor

**Comment by alanihre** [comment]
> @Alv3s @alanihre @LucasFrecia Hi guys, Do you use the go module or vendor tool like `dep` or `govendor`?

I use go modules.

**Comment by sirius1024** [comment]
Go Modules same here. It doesn't work with /v2.
And worked with
```go
import (
	jwt "github.com/appleboy/gin-jwt"
)
...
authMiddware, err := jwt.New(&jwt.GinJWTMiddleware{})
...
```

**Comment by appleboy** [comment]
I can't reproduce the issue. I try the following steps and got nothing. See the [example](https://github.com/appleboy/gin-jwt/blob/master/example/basic/server.go).

```sh
$ go mod init test
$ go mod tidy
$ go run server.go
```

See the `go.mod`

```
module test

go 1.12

require (
	github.com/appleboy/gin-jwt/v2 v2.6.2
	github.com/gin-gonic/gin v1.4.0
)
```

**Comment by tomriddle1234** [comment]
confirm not working, I don't use any package management, just,
go get github.com/appleboy/gin-jwt/v2

**Comment by sirius1024** [comment]
@appleboy Any help for you? Maybe the GOPROXY?

```shell
go env
```

```shell
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kumamon/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/me/go"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.6/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yx/b2wvf4ls6j7cgt2r_m8ttg6h0000gn/T/go-build733860674=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by carloslfu** [comment]
@sirius1024, same here. It worked by replacing the import with `"github.com/appleboy/gin-jwt/v2"`, I hope it helps.

**Comment by appleboy** [comment]
Hi All,

## for go module

```sh
$ go get github.com/appleboy/gin-jwt/v2
```

## without go module

```sh
$ go get github.com/appleboy/gin-jwt
```

I will update the document.
