### ISSUE TITLE
Cookie token is empty in production only but works locally 

### ISSUE THREAD

**Issue by mthizozo** [appleboy/gin-jwt#212]
Hi I am getting this error after deploying my app to openshift
{
    "code": 401,
    "message": "cookie token is empty"
},

but the exact same code works fine when i run it locally. 

I am using Authorization header authentication

**Comment by mthizozo** [comment]
Does this library work differently in production ???

**Comment by appleboy** [comment]
@mthizozo There is no different in production or development. Can you show some detail information or example code?
