### ISSUE TITLE
Question: Why this is code separated from outer scope?

### ISSUE THREAD

**Issue by jimfilippou** [appleboy/gin-jwt#217]
Why this piece of code is like this in the example? 
The fact that we create a new scope has no purpose in this specific example. Is there any reason for this?
```go
auth.Use(authMiddleware.MiddlewareFunc())
{
    auth.GET("/hello", helloHandler)
}
```

**Comment by duaneking** [comment]
It's the perfect example of an authentication only routing configuration.

The code uses the outer scope to better define the security boundaries.
