### ISSUE TITLE
Question: What about asymmetric algorithms in this library?

### ISSUE THREAD

**Issue by Bigyin1** [appleboy/gin-jwt#218]

**Comment by Koichi-hub** [comment]
Read the sources of [GinJWTMiddleware](https://pkg.go.dev/github.com/garnachod/gin-jwt/v2#GinJWTMiddleware), you can specify `PrivKeyFile` and `PubKeyFile` or `PrivKeyBytes` and `PubKeyBytes`, if you keep keys in `.env` file

**Comment by appleboy** [comment]
@Koichi-hub Thank you for helping to explain.
