### ISSUE TITLE
deleted belogik/goes which in go.sum

### ISSUE THREAD

**Issue by dan-leech** [appleboy/gin-jwt#228]
github.com/belogik/goes has not existed anymore, please clean up go.mod and go.sum

**Comment by yenayai** [comment]
Please clean up github.com/belogik/goes as soon as possible. Thanks

**Comment by Kyocfe** [comment]
how can i remove belogik/goes in go.sum file
go.sum file is always auto generated including belogik/goes

**Comment by nickkeers** [comment]
It looks like appleboy's gofight dependency needs to be updated to point to https://github.com/astaxie/beego v1.12.0 which has been updated to use "github.com/OwnLocal/goes v1.0.0" in its go.mod file instead of belogik/goes

**Comment by trileminh94** [comment]
Please merge the pull request as soon as possible. Thanks
