### ISSUE TITLE
Can't find how to access user from protected route

### ISSUE THREAD

**Issue by centralepharma** [appleboy/gin-jwt#23]
I'm trying to access the current userId from a very simple /me route returning the currently logged user informations. I've read in your code that it's supposed to be set at the key "userId" in c, but c.Get("userId") tells me it doesn't exist in my context. What am I doing wrong ?

in main : 
```go
auth := r.Group("/users")
	auth.Use(authMiddleware.MiddlewareFunc())
	{
		auth.GET("/me", user.Me)
		auth.GET("/refresh_token", authMiddleware.RefreshHandler)
	}
```

my handler : 
```go
func Me(c *gin.Context) {
	username, exists := c.Get("userId")

	log.Print(username) //return nil
	log.Print(exists) //return false
}
```

Thx !

**Comment by centralepharma** [comment]
OMG, I'm just so a beginner with go…
```go
payload, _ := c.Get("JWT_PAYLOAD")

p, _ := payload.(map[string]interface{})

id := p["id"].(string)
```

**Comment by appleboy** [comment]
Hi @centralepharma 

Please try the following code:

```go
jwtClaims := ExtractClaims(c)
// get user id.
id := jwtClaims["id"]
```

**Comment by appleboy** [comment]
@centralepharma Any updates?

**Comment by appleboy** [comment]
@centralepharma if you have any updates, please reopen this issue.
