### ISSUE TITLE
not enough arguments in call to c.SetCookie

### ISSUE THREAD

**Issue by lucky51** [appleboy/gin-jwt#240]
![image](https://user-images.githubusercontent.com/27793729/77839036-e85d5b00-71ab-11ea-8eb3-faf69a1fe057.png)

go build  github.com/appleboy/gin-jwt/v2 ..\..\golang\pkg\mod\github.com\appleboy\gin-jwt\v2@v2.6.3\auth_jwt.go:457:14: not enough arguments in call to c.SetCookie

env : go SDK 1.14    ,gin v1.6.0

c.SetCookie(
			mw.CookieName,
			tokenString,
			maxage,
			"/",
			mw.CookieDomain,
			   //http.SameSiteLaxMode,
			mw.SecureCookie,
			mw.CookieHTTPOnly,
		)

**Comment by appleboy** [comment]
@lucky51 Please upgrade gin version to v1.6.2

https://github.com/gin-gonic/gin/releases/tag/v1.6.2
