### ISSUE TITLE
SameSite cookie Flag 

### ISSUE THREAD

**Issue by Djolivald** [appleboy/gin-jwt#247]
Hi,
I know this has been addressed in https://github.com/appleboy/gin-jwt/pull/237 but the PR has been closed without being merged. Now there is https://github.com/appleboy/gin-jwt/pull/242 opened for the Same thing.

Gin 1.6 is out now and the default behaviour in chrome (for now `SameSite=None`) is going to [change as from chrome 76](https://www.chromestatus.com/feature/5088147346030592) (planned for July 30th). Is it possible to get this rolling?
Thanks :D

**Comment by Djolivald** [comment]
Hey @appleboy, sorry to @ you but just wanted to bring out attention on this.

**Comment by appleboy** [comment]
OK I will take it.

**Comment by Djolivald** [comment]
Hey @appleboy, any news on the merge status for this?

**Comment by appleboy** [comment]
@Djolivald Sorry to forget this issue. I will update asap.

**Comment by appleboy** [comment]
See https://github.com/appleboy/gin-jwt/commit/fd0cbae1903aaf9ebdf74a6cfdc1f0fcd5080b34

**Comment by Djolivald** [comment]
@appleboy do you plan on making a release for that? I'm depending on master for now.

**Comment by appleboy** [comment]
@Djolivald See https://github.com/appleboy/gin-jwt/releases/tag/v2.6.4
