### ISSUE TITLE
Change type of Token Claims

### ISSUE THREAD

**Issue by MethDamon** [appleboy/gin-jwt#28]
Hi,

The JWT implementation library you use (https://github.com/dgrijalva/jwt-go) has recently introduced some changes that break some parts of your libary. I think it's just one change (token.Claims is not a map[string]interface{} anymore, but an own type of the dgrijalva library (https://github.com/dgrijalva/jwt-go/blob/master/MIGRATION_GUIDE.md). It would be really great if you could fix this.

Thanks in advance!

**Comment by appleboy** [comment]
I will take it. Thanks for your friendly reminder.

**Comment by MethDamon** [comment]
No problem, thanks for looking into it!

**Comment by appleboy** [comment]
@MethDamon I release `v2.0.0` version which support jwt-go `v3`.

https://github.com/appleboy/gin-jwt#v2-version
