### ISSUE TITLE
wrong gofight path

### ISSUE THREAD

**Issue by majidbl** [appleboy/gin-jwt#284]
there is a issue with gin-jwt and gofight with this error massage
  github.com/appleboy/gin-jwt tested by
        github.com/appleboy/gin-jwt.test imports
        gopkg.in/appleboy/gofight.v2: gopkg.in/appleboy/gofight.v2@v2.1.2: parsing go.mod:
        module declares its path as: github.com/appleboy/gofight/v2
                but was required as: gopkg.in/appleboy/gofight.v2

GOVERSION=go1.16

**Comment by appleboy** [comment]
https://github.com/appleboy/gin-jwt#usage

**Comment by Kolo7** [comment]
Has this problem been solved? I also encountered the same problem.

problem:
github.com/appleboy/gin-jwt tested by
github.com/appleboy/gin-jwt.test imports
gopkg.in/appleboy/gofight.v2: gopkg.in/appleboy/gofight.v2@v2.1.2: parsing go.mod:
module declares its path as: github.com/appleboy/gofight/v2
but was required as: gopkg.in/appleboy/gofight.v2
