### ISSUE TITLE
There is no way to override RefreshHandler

### ISSUE THREAD

**Issue by Koichi-hub** [appleboy/gin-jwt#320]
Before refreshing the access_token, I need to delete the session it refers to so that the hacker cannot quietly use the victim's session. To do this, I need to place the logic of deleting the session somewhere, as well as writing new values to `claims`. But there is no such possibility. 
Was such a scenario not envisaged? Why?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@Koichi-hub You can overwrite the `RefreshResponse` handler.
