### ISSUE TITLE
Fix readme or import

### ISSUE THREAD

**Issue by painhardcore** [appleboy/gin-jwt#40]
Need fix Readme or code, example/server.go imports "github.com/appleboy/gin-jwt" and i don't have it because 

Install gin-gwt v2 version for jwt-go v3 version. To get the package, execute:

$ go get gopkg.in/appleboy/gin-jwt.v2

**Comment by appleboy** [comment]
@painhardcore Done!

**Comment by appleboy** [comment]
@painhardcore Update the example code.
