### ISSUE TITLE
the gin-gonic version is different.

### ISSUE THREAD

**Issue by Yaxian** [appleboy/gin-jwt#50]
Hi, @appleboy 

last tag `v2.1.1`, you use  `github.com/gin-gonic/gin`, but the latest `v2.1.2` you use `gopkg.in/gin-gonic/gin.v1`, the change will broke the program who use `github.com/gin-gonic/gin`

**Comment by appleboy** [comment]
@Yaxian Why the change broke the program? Just update your vendor folder.

**Comment by Yaxian** [comment]
```
cannot use func literal (type func(string, string, *"github.com/gin-gonic/gin".Context) (string, bool)) as type func(string, string, *"gopkg.in/gin-gonic/gin.v1".Context) (string, bool) in field value
```

**Comment by appleboy** [comment]
Could you try https://github.com/appleboy/gin-jwt/blob/master/example/server.go example? I can't reproduce this issue.

**Comment by Yaxian** [comment]
I can't reproduce the issue. thanks! @appleboy
