### ISSUE TITLE
TokenLookup accepts multiple methods

### ISSUE THREAD

**Issue by tngan** [appleboy/gin-jwt#55]
Is it a good practice to allow the lookup having multiple methods instead of a single method only ?

**Comment by appleboy** [comment]
What is your scenario? I can implement this feature.

https://github.com/appleboy/gin-jwt/blob/master/auth_jwt.go#L59-L66

Support multiple methods as following

```
header:<name>,query:<name>
```

separated with `,` symbol

**Comment by tngan** [comment]
@appleboy Just want to know if it is a good practice to relax the constraint.

**Comment by appleboy** [comment]
@tngan I think to depend on your scenario.

**Comment by koolay** [comment]
It is a nice idea, header  token for mobile device and cookie for  browser.
