### ISSUE TITLE
Use with gin v1

### ISSUE THREAD

**Issue by quentin-sommer** [appleboy/gin-jwt#64]
Hi,

I get a signature error while using it with the gin package `"gopkg.in/gin-gonic/gin.v1"`

However If i change gin-jwt gin import from `"github.com/gin-gonic/gin"` to `"gopkg.in/gin-gonic/gin.v1"` it works.

What's the best practice here ?

**Comment by appleboy** [comment]
Hi, @quentin-sommer 

I recommend you change `gopkg.in/gin-gonic/gin.v1` to `github.com/gin-gonic/gin`

see https://github.com/gin-gonic/gin/issues/828

**Comment by quentin-sommer** [comment]
It worked, thank you!
