### ISSUE TITLE
Doesn't build in DOcker

### ISSUE THREAD

**Issue by ShayanJa** [appleboy/gin-jwt#72]
HI i have a BAAS that i built using your gin-jwt to authenticate routes. It works just fine in localhost, 
running it using "go run server.go" , However when i build it using docker i get this error message.

src/work/xprincipia/backend/gin/jwt.go:34: cannot use func literal (type func(string, string, *"gopkg.in/gin-gonic/gin.v1".Context) (string, bool)) as type func(string, string, *"github.com/gin-gonic/gin".Context) (string, bool) in field value
src/work/xprincipia/backend/gin/jwt.go:38: cannot use func literal (type func(string, *"gopkg.in/gin-gonic/gin.v1".Context) bool) as type func(string, *"github.com/gin-gonic/gin".Context) bool in field value
src/work/xprincipia/backend/gin/jwt.go:44: cannot use func literal (type func(*"gopkg.in/gin-gonic/gin.v1".Context, int, string)) as type func(*"github.com/gin-gonic/gin".Context, int, string) in field value

It's wierd because, I didn't get this error last week. Anyways, was it a new update that caused this. Any help would be appreciated

```
// the jwt middleware
var authMiddleware = &jwt.GinJWTMiddleware{
	Realm:      "test zone",
	Key:        []byte("secret key"),
	Timeout:    time.Hour,
	MaxRefresh: time.Hour,
	Authenticator: func(userId string, password string, c *gin.Context) (string, bool) {
		user := gorm.User{}
		passwordBytes := []byte(password)

		if user.GetUserByUsername(userId) {
			hashedPassword := user.HashedPassword
			err := bcrypt.CompareHashAndPassword(hashedPassword, passwordBytes)
			if err == nil {
				glog.Info("USER LOG IN SUCCESSFUL...")
				return userId, true
			}
			glog.Info(err)
		}
		return userId, false
	},
	Authorizator: func(userId string, c *gin.Context) bool {
		//check if this user is in the db based on the jwt
		return gorm.IsUserinDBbyUsername(userId)
	},Unauthorized: func(c *gin.Context, code int, message string) {
		c.JSON(code, gin.H{
			"code":    code,
			"message": message,
		})
	},
	// TokenLookup is a string in the form of "<source>:<name>" that is used
	// to extract token from the request.
	// Optional. Default value "header:Authorization".
	// Possible values:
	// - "header:<name>"
	// - "query:<name>"
	// - "cookie:<name>"
	TokenLookup: "header:Authorization",
	// TokenLookup: "query:token",
	// TokenLookup: "cookie:token",
}
```

Here is jwt.go

**Comment by appleboy** [comment]
@ShayanJa Please change `gopkg.in/gin-gonic/gin.v1` to `github.com/gin-gonic/gin`. See the issue from gin repository.

https://github.com/gin-gonic/gin/issues/828

**Comment by ShayanJa** [comment]
That was the very first thing i did, but It caused different issue, but i figured it out, i pushed the older version i had locally to a github repository and used that for my docker build. thanks for the help
