### ISSUE TITLE
Documentation on accessing payload

### ISSUE THREAD

**Issue by lukeramsden** [appleboy/gin-jwt#73]
How do I access the JWT payload? Nothing seems to work and it isn't documented. #23 didn't work.

**Comment by 0x4E69676874466F78** [comment]
```go
func hello(srv *gin.Context) {
	jwtClaims := ExtractClaims(srv)
	id := jwtClaims["id"].(string)

	srv.JSON(http.StatusOK, gin.H{
		"message": "Hello " + id,
	})
}
```
?

**Comment by lukeramsden** [comment]
@0x4E69676874466F78 The claims are just empty

**Comment by lukeramsden** [comment]
That worked, thanks.

**Comment by cristianchaparroa** [comment]
Well, I'm doing something wrong cause I can't retrieve the `userId` information, I've the following in my handler

```go
func GetAllTransactions(c *gin.Context) {
	jwtClaims := jwt.ExtractClaims(c)
	userId := jwtClaims["id"].(string) //here the jwtClaims give me an error: interface conversion: interface {} is nil, not string
	if userId == "" {
		c.JSON(400,"user_not_found")
		return
	}
	...
}
```
This is the endpoint declaration
```go
s.Api.GET("api/v1/transactions", api.GetAllTransactions, authMiddleware.MiddlewareFunc())
```

And this is the authMiddleware
```go
	authMiddleware := &jwt.GinJWTMiddleware{
		Realm:      "user-zone",
		Key:        []byte("secret"),  
		Timeout:    time.Hour,
		MaxRefresh: time.Hour,
		Authenticator: 	authenticateUser,
		Unauthorized: 	unauthorizedUser,
		TokenLookup: "header:Authorization",
		TokenHeadName: "Bearer",
		TimeFunc: time.Now,
	}
```

**Comment by lukeramsden** [comment]
@cristianchaparroa This is what I did to fix that:

```go
jwtClaimsRaw, _ := c.Get("JWT_PAYLOAD")
jwtClaims := jwtClaimsRaw.(jwt.MapClaims)
username := jwtClaims["id"].(string)
```

**Comment by cristianchaparroa** [comment]
@lukeramsden but the `JWT_PAYLOAD`  does mean that you need to specify the payload function?

**Comment by cristianchaparroa** [comment]
@lukeramsden  if I implement the code that you told me,  the `c.Get("JWT_PAYLOAD")` return a boolean parameter that is in false, then it's does mean that `JWT_PAYLOAD` is not set. What is wrong?

**Comment by lukeramsden** [comment]
@cristianchaparroa Here is my codebase if you want to take a look https://github.com/lukeramsden/go-blog

**Comment by lukeramsden** [comment]
`JWT_PAYLOAD` is set by `authMiddleware.MiddlewareFunc()` (actually in the `middlewareImpl` function).

**Comment by cristianchaparroa** [comment]
@lukeramsden  @0x4E69676874466F78  @appleboy  I don't know what is wrong but I cant retrieve anything with `c.Get("JWT_PAYLOAD")` is always nil `interface conversion: interface {} is nil, not jwt.MapClaims`

**Comment by lukeramsden** [comment]
Do you have your full code on GitHub @cristianchaparroa ?

Also, have you got the auth middleware on the router?

**Comment by cristianchaparroa** [comment]
@lukeramsden  unfortunately I can't share all the code but I share some part the code,  https://gist.github.com/cristianchaparroa/1727d58a9aec8e39a394ed93980ecdea, https://gist.github.com/cristianchaparroa/238c250c61d9485a6624506992802d14

**Comment by lukeramsden** [comment]
@cristianchaparroa On line 29 of `server.go`, you seem to be running your own function BEFORE the auth middleware, could you try putting `authMiddleware.MiddlewareFunc()` first?

**Comment by cristianchaparroa** [comment]
@lukeramsden  you are right! this works, thanks a lot!
