### ISSUE TITLE
the Demo for Login API command is error...

### ISSUE THREAD

**Issue by lemos1235** [appleboy/gin-jwt#75]
It should be "http -v --json POST localhost:8000/login username=admin password=admin", or "curl -v -X POST -H "Content-Type: application/json" -d '{"username":"admin","password":"admin"}' localhost:8000/login"

**Comment by 345161974** [comment]
@lemos1235 Yes, U're right. the command in demo is error.

![command_compare](https://user-images.githubusercontent.com/3973297/27261550-cb39ef56-5477-11e7-8723-749319ac5811.png)

**Comment by appleboy** [comment]
@lemos1235 @345161974 Fixed in #76 Thanks All.
