### ISSUE TITLE
How do I get the username of the logged in user?

### ISSUE THREAD

**Issue by fronbasal** [appleboy/gin-jwt#83]
I am currently dealing with the problem of fetching the username in the auth route group.
How do I do that?

**Comment by nisargap** [comment]
https://godoc.org/github.com/appleboy/gin-jwt
There is an ExtractClaims method that takes in a  gin context you can use that to get the authenticated user information stored in the token

**Comment by fronbasal** [comment]
Thank you for the answer, but there are no methods for getting the username. Just for verifying the token. How to I get the username as a string?

**Comment by nisargap** [comment]
The userId is stored in the claims as a string so if you do
```
func RouteHandler(c *gin.Context) {
   
   claims := jwt.ExtractClaims(c)
   userId := claims["id"]
   // connect to the database and get the username from the userId

}

**Comment by fronbasal** [comment]
Thank you very much! This issue can be closed.

**Comment by appleboy** [comment]
I will update the doc and add `how to get user information` section.

**Comment by fronbasal** [comment]
That would be a great help!

**Comment by appleboy** [comment]
@fronbasal I updated the example section. https://github.com/appleboy/gin-jwt#example
