### ISSUE TITLE
User Info into Gin Default Logger

### ISSUE THREAD

**Issue by eduardohitek** [appleboy/gin-jwt#92]
Hi All, I'm trying to include the logged user info into Gin Default Log, but Go won't allow me to include the gin-jwt import into logger.go file, because it creates "import cycle".
Has anyone faced this?

Thanks in Advance.

**Comment by huyntsgs** [comment]
I think you can re-write logger.go and get userInfo from gin.Context (remember to put userInfo to gin.Context before so that your logger can use)

**Comment by appleboy** [comment]
This is not gin-jwt issue.
