### ISSUE TITLE
Supporting additional params to the Authenticator

### ISSUE THREAD

**Issue by charl** [appleboy/gin-jwt#94]
At the moment the Authenticator has the following signature: func(username string, password string, c *gin.Context).

This works perfectly when you only have a username/password that you'd like to auth on. In our use case we have a username/password but also need to auth an OTP.

Even though the GIN context is being passed down to the Authenticator one does not have access to the c.Request.Body if you wanted to manually parse out any extra params because the c.Request.Body has already been read and cleared by the time it gets to the Authenticator.

It would be preferable to do the auth in one request instead of first getting a JWT token and then doing the OTP auth separate.

Is additional parameter handling a feature that can be added to gin-jwt or is this something that I need to try and fudge in using middleware that copies the c.Request.Body and records it in the context?

**Comment by gonboy** [comment]
1. **maybe can add header.  change like this**
```go
// auto_jwt.go
1.  
PayloadFunc func(userID string, c *gin.Context) map[string]interface{}

2. if mw.PayloadFunc != nil {
    for key, value := range mw.PayloadFunc(loginVals.Username, c) {
	claims[key] = value
    }
}
3. disable func 
TokenGenerator
```
2.  **so you can  use like belown to get parameters**
```
c.Request.getHead(....)
```

**Comment by Marlon-Monroy** [comment]
I think you would write your own handler instead. After all this only proves the very basics and most of the time you'll end up with more params or less.

**Comment by RPiAwesomeness** [comment]
This is also an issue I'm running into, I need to extract data from the request JSON. Is there any way that we can override the function that's extracting the request JSON or make it so it returns the data? It would be really handy if we could provide a struct of our own to be filled instead of using the hardcoded Login object, since it's emptying the body buffer entirely.

**Comment by appleboy** [comment]
Hi @charl @Marlon-Monroy @RPiAwesomeness Now you can customer your `Authenticator` function. See the following example. I remove the `username string, password string` parameter.

https://github.com/appleboy/gin-jwt/blob/9ad0d889e6862356f48b836107fbc6d030e864ae/example/server.go#L49-L81
